version: '3.8'
services:
  redis-session:
    image: redis:alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --requirepass ${REDIS_PASSWORD}
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}

  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - '8080:8080'
    environment:
      SESSION_SECRET: ${SESSION_SECRET}